services:
  - type: web
    name: cyberlegal-ai
    runtime: node
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
